name: value_t2_annotation
description: annotation for value_t2_generator which provides a short syntax, value type (ish) way of creating classes
version: 1.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

#dependency_overrides:
#  adi_helpers:
#    path: ../../adi_helpers

dependencies:
  adi_helpers:
    git:
      url: https://github.com/atreeon/adi_helpers
      ref: master
  collection: ^1.18.0
  dartx: ^1.2.0
#  adi_helpers:
#    path: ../../adi_helpers

#  quiver: ^3.0.1
#  collection: ^1.15.0-nullsafety.5

homepage: https://github.com/atreeon/value_t2
