name: example

environment:
  sdk: ">=3.1.3 <4.0.0"

dependency_overrides:
  adi_helpers:
    path: ../../adi_helpers

dependencies:
  meta: any
  mock_creator_annotation: ^1.0.2-nullsafety3
#  quiver_hashcode:
#    git: https://github.com/atreeon/quiver_hashcode
#  value_t2_annotation: ^1.0.7-nullsafety.3
  value_t2_annotation:
    path: ../value_t2_annotation
  adi_helpers:
    path: ../../adi_helpers

dev_dependencies:
  build_runner: ^2.4.6
  test: ^1.24.8
  value_t2_generator:
    path: ../value_t2_generator/
