name: example

environment:
  sdk: ">=2.6.1 <3.0.0"

dependencies:
  value_t2_annotation: ^1.0.4
  quiver_hashcode: ^2.0.0
  meta: any

dev_dependencies:
  build_runner: ^1.7.3
  test: ^1.12.0
#  copy_with_e_generator: ^1.0.2
  value_t2_generator:
    path: ../value_t2_generator/