name: example

#environment:
#  sdk: ">=2.6.1 <3.0.0"

dependencies:
  value_t2_annotation:
    path: ../value_t2_annotation/
  copy_with_e_annotation: ^1.0.1

dev_dependencies:
  build_runner: ^1.7.3
  test: ^1.12.0
  copy_with_e_generator: ^1.0.2
  value_t2_generator:
    path: ../value_t2_generator/