name: example

environment:
  sdk: ">=3.1.3 <4.0.0"

#  adi_helpers:
#    path: ../../adi_helpers

#dependency_overrides:
#  value_t2_annotation:
#    path: ../value_t2_annotation

dependencies:
  meta: any
  mock_creator_annotation: ^1.0.2-nullsafety3
  value_t2_annotation:
    git:
      url: https://github.com/atreeon/value_t2.git
      ref: master
      path: value_t2_annotation
  adi_helpers:
    git:
      url: https://github.com/atreeon/adi_helpers
      ref: master
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  tuple: ^2.0.2
  collection: ^1.18.0

dev_dependencies:
  build_runner: ^2.4.6
  test: ^1.24.8
  value_t2_generator:
    path: ../value_t2_generator
