name: clear_dirs
description: A simple command-line application.

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  path: ^1.7.0
  args: 1.6.0
  process_run: 0.10.9

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.14.3
