name: example_dartway

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  value_t2_annotation: ^1.0.6
#   path: ../value_t2_annotation/
  quiver_hashcode: ^2.0.0
  meta: any

dev_dependencies:
  build_runner: ^1.7.3
  test: ^1.16.0-nullsafety.16
#  copy_with_e_generator: ^1.0.2
  value_t2_generator:
    path: ../value_t2_generator/