#!/bin/sh

GIT_DIR=`git rev-parse --git-dir`
WORKING_DIR=${GIT_DIR/*"worktrees/"}

cd example

pub run test > /dev/null 2>&1

EXIT_CODE_LAST=$?
#echo "pub run test example: ${EXIT_CODE_LAST}"
if [ $EXIT_CODE_LAST != "0" ] ; then
  echo "example testing failed"
  exit 1; fi;

cd ..
cd value_t2_generator

pub run test > /dev/null 2>&1
EXIT_CODE_LAST=$?
#echo "pub run test value_t2_generator: ${EXIT_CODE_LAST}"
if [ $EXIT_CODE_LAST != "0" ] ; then
  echo "value_t2_generator testing failed"
  exit 1; fi;

echo "success"
exit 0
