targets:
  $default:
    builders:
      value_t2_generator|value_t2:
        enabled: true

builders:
  value_t2:
    target: ":value_t2_generator"
    import: "package:value_t2_generator/value_t2_generator.dart"
    builder_factories: ["valueT2Builder"]
    build_extensions: {".dart": [".valuet2.part"]}
    auto_apply: dependents
    build_to: source
    runs_before: ["mock_creator_generator:mock_creator"]


#    applies_builders: ["source_gen|combining_builder"]
#
#
#builders:
#  freezed:
#    import: "package:freezed/builder.dart"
#    builder_factories: ["freezed"]
#    build_extensions: { ".dart": [".freezed.dart"] }
#    auto_apply: dependents
#    build_to: source
#    runs_before: ["json_serializable|json_serializable"]