name: value_t2_generator
description: Provides a short syntax, value type (ish) way of creating classes - copywith, toString, equality
version: 1.0.27-nullsafety23
homepage: https://github.com/atreeon/value_t2

environment:  
  sdk: ">=2.8.1 <3.0.0"

# testing did take 24s for 58 tests

#dependency_overrides:
#  adi_helpers:
#    path: ../../../dart/adi_helpers

dependencies:  
  adi_helpers:
    path: ../../../dart/adi_helpers
  analyzer: '>=1.7.0 <=3.0.0'
  build: ^2.1.0
  source_gen: ^1.1.1
  dartx: ^0.6.0
  generator_common:
    path: ../../generator_common/
  value_t2_annotation:
    path: ../value_t2_annotation

dev_dependencies:
  build_runner: ^2.1.4
  test: ^1.18.2