name: value_t2_generator
description: Provides a short syntax, value type (ish) way of creating classes - copywith, toString, equality
version: 1.1.0
homepage: https://github.com/atreeon/value_t2

environment:
  sdk: ">=3.1.3 <4.0.0"

# testing did take 24s for 58 tests

#dependency_overrides:
#  adi_helpers:
#    path: ../../../dart/adi_helpers

dependencies:
  #  adi_helpers:
  #    path: ../../../dart/adi_helpers
  analyzer: '>=5.12.0 <=6.0.0'
  build: ^2.1.0
  source_gen: ^1.1.1
  dartx: ^1.2.0
  generator_common: '>=1.0.0 <=2.0.0'
  value_t2_annotation: '>=1.0.0 <=2.0.0'

dev_dependencies:
  build_runner: ^2.4.6
  test: ^1.24.8