name: value_t2_generator
description: Provides a short syntax, value type (ish) way of creating classes - copywith, toString, equality
version: 1.0.27-nullsafety14
homepage: https://github.com/atreeon/value_t2
 
environment:  
  sdk: ">=2.8.1 <3.0.0"
  
dependencies:  
  build: ^1.6.3
  source_gen: ^0.9.10+3
  value_t2_annotation: ^1.0.7-nullsafety.2
  dartx: ^0.6.0
  analyzer: '>=0.40.0 <=1.0.0'
  copy_with_e_generator: ^1.0.10-nullsafety13
  analyzer_models: ^1.0.8
  adi_helpers: ^1.0.7-nullsafety

dev_dependencies:  
  build_runner: ^1.7.3
  test: ^1.11.1