name: value_t2_generator
description: Provides a short syntax, value type (ish) way of creating classes - copywith, toString, equality
version: 1.0.22
homepage: https://github.com/atreeon/value_t2
 
environment:  
  sdk: ">=2.8.1 <3.0.0"
  
dependencies:  
  build: ^1.2.2
  source_gen: ^0.9.5
  value_t2_annotation: ^1.0.6
#    path: ../value_t2_annotation/
  dartx: '>=0.3.0 <0.7.0'
  basic_utils: ^2.4.8
  analyzer: '>=0.39.5 <0.40.0'
  copy_with_e_generator: ^1.0.7
  analyzer_models: ^1.0.8

dev_dependencies:  
  build_runner: ^1.7.3
  test: ^1.11.1

#  pub run build_runner build --delete-conflicting-outputs && for d in ../*/; { pub run test "$d"; } && say "done"