name: value_t2_generator
description: Provides a short syntax, value type (ish) way of creating classes - copywith, toString, equality
version: 1.0.27-nullsafety23
homepage: https://github.com/atreeon/value_t2

environment:  
  sdk: ">=2.8.1 <3.0.0"

#dependency_overrides:
#  adi_helpers:
#    path: ../../../dart/adi_helpers

dependencies:  
#  adi_helpers: ^1.0.7-nullsafety
  adi_helpers:
    path: ../../../dart/adi_helpers
  analyzer: '>=1.7.0 <=1.7.1'
  build: ^1.6.3
  #^1.0.10-nullsafety13
#  copy_with_e_generator:
#    path: ../../copy_with_e/copy_with_e_generator
  dartx: ^0.6.0
  generator_common:
    path: ../../generator_common/
  #1.0.0-nullsafety8
  source_gen: ^0.9.10+3
  value_t2_annotation:
    path: ../value_t2_annotation

dev_dependencies:  
  build_runner: ^1.7.3
  test: ^1.11.1