name: value_t2_generator
description: Creates copyWith extension methods for each annotated class and works with abstract too.
version: 1.0.2
homepage: https://github.com/atreeon/ValueT2
 
environment:  
  sdk: ">=2.6.1 <3.0.0"
  
dependencies:  
  build: ^1.2.2
  source_gen: ^0.9.4+7
  value_t2_annotation:
    path: ../value_t2_annotation/
  dartx: ^0.3.0
  quiver: ^2.0.1
  dartz: ^0.8.3
  basic_utils: ^2.4.8
  analyzer: '>=0.39.4 <0.40.0'
  copy_with_e_generator: ^1.0.2

#  adi_helpers:
#    path: ../../../dart/adi_helpers/

dev_dependencies:  
  # build_test: ^0.10.0  
  build_runner: ^1.7.3
  test: ^1.11.1
  