name: value_t2_generator
description: Creates copyWith extension methods for each annotated class and works with abstract too.
version: 1.0.3
homepage: https://github.com/atreeon/ValueT2
 
environment:  
  sdk: ">=2.6.1 <3.0.0"
  
dependencies:  
  build: ^1.2.2
  source_gen: ^0.9.4+7
  value_t2_annotation: ^1.0.2
  dartx: ^0.3.0
  basic_utils: ^2.4.8
  analyzer: '>=0.39.4 <0.40.0'
  copy_with_e_generator: ^1.0.4
  analyzer_models: ^1.0.3

dev_dependencies:  
  build_runner: ^1.7.3
  test: ^1.11.1
  