name: analyzer_models
description: A number of DTOs to help simplify analyzer models and make testing easier - valueT2, copywithe, createfrome
version: 1.0.3

environment:  
  sdk: ">=2.6.1 <3.0.0"

homepage: https://github.com/atreeon/value_t2
