name: analyzer_models
description: A number of DTOs to help simplify analyzer models and make testing easier - valueT2, copywithe, createfrome
version: 1.0.1

environment:  
  sdk: ">=2.6.1 <3.0.0"

dependencies:

dev_dependencies:  
  test: 1.3.4

homepage: https://github.com/atreeon/ValueT2
