name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  dart:latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup value_t2_generator
        working-directory: ./value_t2_generator
        run:  |
          pub get
          pub run build_runner build --delete-conflicting-outputs
      - name: Run tests value_t2_generator
        working-directory: ./value_t2_generator
        run: pub run test
      - name: Setup example
        working-directory: ./example
        run:  |
          pub get
          pub run build_runner build --delete-conflicting-outputs
      - name: Run tests Example
        working-directory: ./example
        run: pub run test

